### ISSUE TITLE
error

### ISSUE THREAD

**Issue by cmdocmd** [futile/enet-rs#8]
![d2](https://user-images.githubusercontent.com/55096480/84594239-0446d380-ae62-11ea-9220-cd6ee308305a.PNG)

![d2](https://user-images.githubusercontent.com/55096480/84594248-16287680-ae62-11ea-8b4f-8d1a44df4bb9.PNG)

![d2](https://user-images.githubusercontent.com/55096480/84594258-22accf00-ae62-11ea-9af8-97e36b7e1229.PNG)

everything is from this repo 
just changed the port and made it UNSPECIFIED instead of localhost

**Comment by futile** [comment]
Hi, were you able to solve your issue? :)

**Comment by cmdocmd** [comment]
not really still wondering why its not working

**Comment by futile** [comment]
You can also try cloning this repo and then running `cargo run --example server` and `cargo run --example client` and see if those work. I'll try your adjustments locally as well.

**Comment by futile** [comment]
Ok, so if all I do is change the listening IP address to `Ipv4Addr::UNSPECIFIED`, the example server and client still continue to work fine.

Try cloning this repo and running both the example server and client with `RUST_BACKTRACE=1` (have to set this as an environment variable) so we can see where exactly it crashes.

**Comment by cmdocmd** [comment]
ok so i want to make sure that im doing everything correctly so first thing i added enet 0.2.3
![d2](https://user-images.githubusercontent.com/55096480/84598729-e5563a80-ae7d-11ea-841c-a22b4b04b3cc.PNG)

then i added in main.rs example of server:
![d2](https://user-images.githubusercontent.com/55096480/84598775-336b3e00-ae7e-11ea-956e-fa03a7585505.PNG)
and i have changed the port to 17091 and the ip to UNSPECIFIED
then i builded it

**Comment by cmdocmd** [comment]
![d2](https://user-images.githubusercontent.com/55096480/84599043-336c3d80-ae80-11ea-8c76-a69bd7579fa9.PNG)

but if i try to make rustc main.rs i get this error

**Comment by cmdocmd** [comment]
![d2](https://user-images.githubusercontent.com/55096480/84600423-30764a80-ae8a-11ea-8e53-4ac90ee64f5e.PNG)

i tried to make cargo test got this error

**Comment by cmdocmd** [comment]
and here when i enabled rust_backtace=1
https://pastebin.com/ZT4W94j8
and i didnt change anything from this repo just installed it 
made cargo build
then cargo test

**Comment by futile** [comment]
So it seems that `enet_address_set_host()` in `src/address.rs:29` seems to return an error. The ENet-function that is called there is this one: http://enet.bespin.org/group__Address.html#ga979aff1766944d841950c35b57705b49

This is really weird and seems to be some enet-internal problem. You can try changing the address it tries to bind to from `"localhost"` to `"127.0.0.1"` in the test (so in line 86 in `address.rs`). That also works locally for me as well, don't really see what's going wrong here.

**Comment by cmdocmd** [comment]
![d2](https://user-images.githubusercontent.com/55096480/84601605-7afbc500-ae92-11ea-9ec9-c78e50cdf1b5.PNG)

okay when i changed it to 127.0.0.1 and run cargo test it didnt show any error but when i tried to connect still doesn't receive any event

**Comment by cmdocmd** [comment]
update: it is receiving  packet from client now but is it possible to receive packet from a game ?

**Comment by futile** [comment]
That's great to hear! Sorry I didn't reply for a while. Was there some error in this library that caused the problem? And what exactly do you mean by 'receiving a packet from a game'? Does the example client successfully send a packet to the server, which then prints a message?
